In [10]:
import torch


In [11]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)# tensor에는 변수가 1개 들어가야 함, 또한 랭크 2의 2차원 행렬임을 알 수 있다 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [12]:
#텐서의 형태는 size()혹은 shape를 이용해서 확인할 수 있다. 단순히 랭크만 확인할 예정이라면 ndimension함수
print('size', x.size())
print('shape',x.shape)
print('랭크(차원)',x.ndimension())

size torch.Size([3, 3])
shape torch.Size([3, 3])
랭크(차원) 2


In [13]:
#unsqueeze(), squeeze(),view( )함수로 텐서의 랭크와 shape를 변경할 수 있다.
x = torch.unsqueeze(x,0) #랭크 업
print(x)
print('size', x.size())
print('shape',x.shape)
print('랭크(차원)',x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
size torch.Size([1, 3, 3])
shape torch.Size([1, 3, 3])
랭크(차원) 3


In [14]:
x = torch.squeeze(x) #랭크 다운
print(x)
print('size', x.size())
print('shape',x.shape)
print('랭크(차원)',x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
size torch.Size([3, 3])
shape torch.Size([3, 3])
랭크(차원) 2


In [15]:
x = x.view(9) #9모양인 텐서로 변형시킴 (1차원), 랭크 다운 and shape변형
print(x)
print('size', x.size())
print('shape',x.shape)
print('랭크(차원)',x.ndimension())
#이처럼 squeeze,unsqueeze,view함수는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절할 수 있다.
#갯수를 변화시키지 못하는 점 ! 변화시켜는 부분이 보이면 에러가 발생한다.

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
size torch.Size([9])
shape torch.Size([9])
랭크(차원) 1
